config/routes.rb
Hoardle::Application.routes.draw do
  get "rest_api/create_link"
  resources :categories

  resources :links
  get "home/index"
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :links
  has_and_belongs_to_many :tags
  belongs_to :user, foreign_key: :owner_id
  validates :name, :user, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :tags
  validates :link, presence: true

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :categories, join_table: "categories_tags"
  has_and_belongs_to_many :links, join_table: "links_tags"
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
    @categories = Category.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def link_params
    params.require(:link).permit(:link, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create

  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  
  def new
    
  end
  
  
  def check_permissions
    authorize! :create, resource
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Hoardle, make link sharing easy!</h1>
  <p>Do you know the stupid moment you are browsing on your smartphone and you want to share a link with another device.</p>
  <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
</div

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to("Hoardle",root_path, class: "navbar-brand")%>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav ">
					<%if user_signed_in?%>
				
					<li>
						<%= link_to("Links", links_path)%>
					</li>
					<%end%>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<%if user_signed_in?%>
					<li><%=link_to("Settings", edit_user_registration_path)%></li>
					<li><%=link_to("Logout",   destroy_user_session_path , method: "DELETE")%></li>

					<%else%>
					<li>
						<%= link_to("Sign In", new_user_session_path) %>
					</li>
					<li>
						<%= link_to("Sign Up", new_user_registration_path) %>
					</li>
					<%end%>
				</ul>
			</div>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Hoardle</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render partial: "layouts/navigation" %>
		<div class="container">
			<% if notice %>
			<p class="alert alert-success">
				<%= notice %>
			</p>
			<% end %>
			<% if alert %>
			<p class="alert alert-danger">
				<%= alert %>
			</p>
			<% end %>
			<%= yield %>

		</div>
	</body>
</html>

app/views/links/index.html.erb
<div class="col-md-2">
	<div class="list-group">
		<%@categories.each do |category|%>
		<a class="list-group-item" href="#"><%= icon("folder-o")%>&nbsp; <%= category.name%></a>
		<%end%>
	</div>
</div>
<div class="col-md-10">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">

				<div class="col-md-4">
					<img src="" alt="test" class="img-rounded">
				</div>
				<div class="col-md-6">
					user

				</div>
				<div class="col-md-2">
					<%= icon("lock")%>
				</div>
			</div>
			<div class="row"></div>
		</div>
	</div>
	<div class="row form-group">
		<ul class="list-group">
			<li class="list-group-item">
				<%= text_field_tag("link", "", class: "form-control", placeholder: "http://ficken.bumsen")%>
			</li>
			<li class="list-group-item">
				<%= text_field_tag("tag", "", class: "form-control", placeholder: "ficken, bumsen, vögeln")%>
			</li>
		</ul>
	</div>

	<% @links.each do |link|%>
	<div class="row">
		<div class="col-md-11">
			<ul class="list-group">
				<li class="list-group-item">
					<%= link.link %>
				</li>
				<li class="list-group-item">
					<%link.tags.each do |t|%>
					<div style="display: inline-block">
						<span class="badge"><%= t.name %></span>
					</div>
					<%end%>
				</li>
			</ul>

		</div>
		<div class="col-md-1">
			<div class="panel panel-default">
				<div class="panel-body">
					<%= link_to("delete", confirm: "Are you sure?") do %>
					<%= icon("times-circle fa-2x")%>
					<%end%>
				</div>
			</div>
		</div>
	</div>
	<%end%>
</div>